Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#DataFrame yang akan digunakan
target_data = pd.concat((target,target1), axis = 1)
#Mengganti Nama Kolom dari dataframe target_data
target_data.columns = ["value_petal_width", "category_petal_width"]
target_data
------------------

[0;31m[0m
[0;31mNameError[0mTraceback (most recent call last)
[0;32m<ipython-input-17-854903ead71b>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m#DataFrame yang akan digunakan[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mtarget_data[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mconcat[0m[0;34m([0m[0;34m([0m[0mtarget[0m[0;34m,[0m[0mtarget1[0m[0;34m)[0m[0;34m,[0m [0maxis[0m [0;34m=[0m [0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;31m#Mengganti Nama Kolom dari dataframe target_data[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mtarget_data[0m[0;34m.[0m[0mcolumns[0m [0;34m=[0m [0;34m[[0m[0;34m"value_petal_width"[0m[0;34m,[0m [0;34m"category_petal_width"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mtarget_data[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'target' is not defined
NameError: name 'target' is not defined

